apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: conversor-temperatura
  template:
    metadata: 
      labels:
        app: conversor-temperatura
    spec: 
      containers:
        - name: conversor-temperatura
          image: eduardolfalcao/conversao-temperatura:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: conversor-temperatura
spec:
  selector:
    app: conversor-temperatura
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
  type: NodePort
